logdir: data/checkpoints/conll2019_wiki_00001
debug: False
device: 0
eval_device: 0
dataset: EDLDataset
model: Net
data_version_name: conll2019
wiki_lang_version: enwiki
eval_on_test_only: False
out_device: 0
batch_size: 6
eval_batch_size: 1
accumulate_batch_gradients: 8
sparse: True
encoder_lr: 5e-05
decoder_lr: 0.1
maskout_entity_prob: 0.0
segm_decoder_lr: 0.001
encoder_weight_decay: 0.0
decoder_weight_decay: 0.0
segm_decoder_weight_decay: 0.0
learn_segmentation: False
label_size: 8192
entity_embedding_size: 768
project: False
n_epochs: 20
collect_most_popular_labels_steps: 1
checkpoint_eval_steps: 10000
checkpoint_save_steps: 100000
finetuning: 3
top_rnns: False
train_loc_file: train.loc
valid_loc_file: valid.loc
resume_reset_epoch: False
resume_optimizer_from_checkpoint: False
topk_neg_examples: 20
dont_save_checkpoints: False
data_workers: 24
eval_before_training: False
train_data_dir: data
valid_data_dir: data
test_data_dir: data
