logdir:  data/checkpoints/conll2019_aidaconll_00001/
resume_from_checkpoint: data/checkpoints/conll2019_wiki_00001/best_f1-0.pt
resume_reset_epoch: True
data_path_conll: data/benchmarks/aida-yago2-dataset/conll_dataset_dummy_254-20.pickle
data_version_name: dummy
collect_most_popular_labels_steps:  1
checkpoint_eval_steps:  10000
checkpoint_save_steps:  1000
device: 0
eval_device: 0
out_device: 0
dataset: CONLLEDLDataset
model: ConllNet
batch_size:  2
accumulate_batch_gradients: 4
eval_batch_size:  3
label_size: 1024
topk_neg_examples: 20
finetuning:  1
sparse:  True
encoder_lr:  5e-5
decoder_lr:  0
n_epochs: 60
segm_decoder_lr:	0
segm_decoder_weight_decay:	1e-10
learn_segmentation: False
bert_dropout: 0.2
maskout_entity_prob: 0
eval_before_training: False
project: False
exclude_parameter_names_regex: 'embeddings|encoder\.layer\.[0-2]\.'
